### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by aloasut** [chenyueban/firefly#21]
### Search before asking

- [X] 在 [issues](https://github.com/chenyueban/firefly/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/chenyueban/firefly/issues) and found nothing similar.

### feature

建议添加收藏夹功能

### 描述 Motivation

兄弟好，单枪匹马做笔记功能路漫漫，建议转型为bookmark、tab的收藏功能，or新建一个项目

大概思路：
1.插件 post url、摘要 到 server
2.server 用无头浏览器抓页面，文本分析后存入向量数据库
3.可以用ai分析这个页面是干啥的并做摘要/加tag
4.日后就可以用自然语言来找自己收藏的东西了

可以用开源+云服务的方式来收费

### Solution

na

### 还有其他内容吗？Anything else?

na

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by chenyueban** [comment]
非常感谢你的建议, 你的思路很有趣 我也受到了一些启发, 讲一下现在我对这个项目的定位和想法吧
1. 这只是一个收集信息的工具, 正如你所说单枪匹马做笔记功能路漫漫. 我更愿意把收集信息这个流程做的更易用些, 至于文字的深度挖掘,文字编辑这些能力还是用更专业的工具 例如 notion
2. 为了更符合这个定位 后续打算对接一些 专业的笔记工具, 方便将 Firefly 中的数据快速流向 笔记工具
3. 你提到的爬取 url 信息 存入向量数据库 用 ai 生成摘要, 这个点很有意思 如果方便可以邀请你继续讨论下么

方便的话可以加下tg讨论
https://t.co/cjiEx7hd8e
或者 discord 也可以
https://discord.gg/qxqNEGyH3k

欢迎其他同学加入一起讨论
